buddy8800: card Class Reference
card Class Reference abstract
Base class for all cards.
#include <card.hpp>
Public Member Functions
Bit utilities.
void set_bit (u16 adr, u8 bitmask)
Set a bit in a byte on the bus.
void unset_bit (u16 adr, u8 bitmask)
Unset a bit in a byte on the bus.
void set_if_bit (u16 adr, u8 bitmask, bool value)
Un/set a bit in a byte on the bus by condition.
Commonly used methods.
bool is_w_locked () const
Check if the card is write-locked.
void w_lock ()
Lock the card for writing.
void w_unlock ()
Unlock the card for writing.
bool is_irq () const
Check if the card has an IRQ raised.
void raise_irq (bool value)
Raise or clear the IRQ trigger.
Abstract methods.
virtual bool in_range (u16 adr) const =0
Check if an address on the bus is in the card's range.
virtual card_identify identify ()=0
Get information about the card.
virtual u8 read (u16 adr) const =0
Read a byte from the card.
virtual void write (u16 adr, u8 byte)=0
Write a byte to the card.
virtual void write_force (u16 adr, u8 byte)=0
Write a byte to the card regardless of write lock.
virtual bool is_io () const =0
Check if the card is an I/O card.
virtual void refresh ()=0
Refresh the card to allow periodic I/O, timer or sync operation.
virtual std::array< u8, 3 > get_irq ()=0
Get the IRQ instruction (and possible operands).
virtual void clear ()=0
Clears the card data or configuration.
Protected Attributes
bool write_locked = false
bool irq_raised = false
Detailed Description
Base class for all cards.
This class is the base class for all cards, it provides a set of methods that should be implemented by all cards that want to interface with the bus class. It also provides some prepared methods that can be used by the bus or the card itself to handle some common operations.
Member Function Documentation
get_irq()
virtual std::array<u8, 3> card::get_irq () pure virtual
Get the IRQ instruction (and possible operands).
See also
bus::get_irq()
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by bus::get_irq().
identify()
virtual card_identify card::identify () pure virtual
Get information about the card.
Returns
A card_identify struct with lengthy details about the card.
Implemented in serial_card, and data_card< construct_then_write_lock >.
in_range()
virtual bool card::in_range (u16 adr) const pure virtual
Check if an address on the bus is in the card's range.
Parameters
adr The address to check.
Returns
True if the address is in the card's range, false otherwise.
Note
This method should always be used when interacting with cards from the bus, to avoid out of range accesses. It is not used by the cards themselves to avoid double checking.
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by bus::read(), bus::write(), and bus::write_force().
is_io()
virtual bool card::is_io () const pure virtual
Check if the card is an I/O card.
Returns
False on a memory card, true on an I/O card.
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by bus::read(), bus::write(), and bus::write_force().
read()
virtual u8 card::read (u16 adr) const pure virtual
Read a byte from the card.
Parameters
adr The address to read from.
Returns
The byte read from the card.
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by bus::read(), set_bit(), and unset_bit().
refresh()
virtual void card::refresh () pure virtual
Refresh the card to allow periodic I/O, timer or sync operation.
See also
bus::refresh()
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by bus::refresh().
set_bit()
void card::set_bit (u16 adr, u8 bitmask) inline
Set a bit in a byte on the bus.
Warning
This method does not check if the address is in the card's range.
References read(), and write().
Referenced by set_if_bit().
set_if_bit()
void card::set_if_bit (u16 adr, u8 bitmask, bool value) inline
Un/set a bit in a byte on the bus by condition.
Warning
This method does not check if the address is in the card's range.
References set_bit(), and unset_bit().
unset_bit()
void card::unset_bit (u16 adr, u8 bitmask) inline
Unset a bit in a byte on the bus.
Warning
This method does not check if the address is in the card's range.
References read(), and write().
Referenced by set_if_bit().
write()
virtual void card::write (u16 adr, u8 byte) pure virtual
Write a byte to the card.
Parameters
adr The address to write to.
byte The byte to write.
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by set_bit(), unset_bit(), and bus::write().
write_force()
virtual void card::write_force (u16 adr, u8 byte) pure virtual
Write a byte to the card regardless of write lock.
Parameters
adr The address to write to.
byte The byte to write.
Implemented in serial_card, and data_card< construct_then_write_lock >.
Referenced by bus::write_force().
The documentation for this class was generated from the following file:
src/core/bus/card.hpp