buddy8800: serial_card Class Reference
serial_card Class Reference
A card that emulates a 6850 ACIA.
#include <card.hpp>
Public Member Functions
serial_card (u16 start_adr, usize base_clock=SERIAL_BASE_CLOCK)
bool in_range (u16 adr) const override
Check if an address on the bus is in the card's range.
card_identify identify () override
Get information about the serial card.
u8 read (u16 adr) override
Read a byte from the serial registers.
void write (u16 adr, u8 byte) override
Write a byte to the serial registers.
bool is_io () const override
Check if the card is an I/O card.
void clear () override
Clear the serial card state and configuration.
Unused methods.
void write_force (u16 adr, u8 byte) override
Write a byte to the card regardless of write lock.
std::array< u8, 3 > get_irq () override
Get the IRQ instruction (and possible operands).
Public Member Functions inherited from card
bool is_w_locked () const
Check if the card is write-locked.
void w_lock ()
Lock the card for writing.
void w_unlock ()
Unlock the card for writing.
bool is_irq () const
Check if the card has an IRQ raised.
void raise_irq (bool value)
Raise or clear the IRQ trigger.
Additional Inherited Members
Protected Attributes inherited from card
bool write_locked = false
bool irq_raised = false
Detailed Description
A card that emulates a 6850 ACIA.
Parameters
start_adr The starting address of the card.
base_clock The base clock speed of the UART (it can be further divided), default is SERIAL_BASE_CLOCK.
This card handles interaction with a pseudo-terminal connected to the card UART. Emulation follows the Motorola 6850 ACIA (Asynchronous Communications Interface Adapter) specifications, but quite simplified. The card has 4 I/O addresses that correspond to the TX_DATA (write-only), RX_DATA (read-only), CONTROL (write-only) and STATUS (read-only) registers of the UART. The card is also able to trigger IRQ according to different conditions.
Note
The state of I/O devices is updated upon each read or write operation, instead of running a refresh cycle as previously done.
Note
To mimic the partial address decode behavior, while the IN and OUT instructions of the 8080 duplicate the argument byte on the address bus, the decoder only looks at the lower 8 bits, effectively creating 255 mirrors of the card in the address space. This is expected behavior.
Warning
Out of range addresses are not checked, they should be checked by the bus instead, to avoid calling in_range() twice.
Member Function Documentation
get_irq()
std::array<u8, 3> serial_card::get_irq () inline override virtual
Get the IRQ instruction (and possible operands).
See also
bus::get_irq()
Implements card.
identify()
card_identify serial_card::identify () inline override virtual
Get information about the serial card.
Note
The detail contains the base clock, control register (hex) and the pseudo-terminal name.
Implements card.
References pty::name(), and util::to_hex_s().
read()
u8 serial_card::read (u16 adr) inline override virtual
Read a byte from the serial registers.
Returns
The byte read from the serial registers, or BAD_U8 if the address is invalid (which should be prevented by in_range()).
Implements card.
References pty::getch(), and pty::poll().
write()
void serial_card::write (u16 adr, u8 byte) inline override virtual
Write a byte to the serial registers.
Note
This method will also handle the UART configuration by writing to the CONTROL register.
Implements card.
References pty::set_baud_rate(), and pty::setup().
Referenced by write_force().
write_force()
void serial_card::write_force (u16 adr, u8 byte) inline override virtual
Write a byte to the card regardless of write lock.
Parameters
adr The address to write to.
byte The byte to write.
Implements card.
References write().
The documentation for this class was generated from the following file:
src/core/bus/card.hpp