buddy8800: cpu< bus_iface > Class Template Reference
cpu< bus_iface > Class Template Reference
Represents the CPU of the emulator.
#include <cpu.hpp>
Public Member Functions
cpu (bus_iface init_adr_space)
CPU API methods.
void step (usize steps=1)
Steps the CPU by one instruction (and its operands).
void execute (u8 opcode, u8 operand1, u8 operand2=0)
Executes a single opcode with one or two operands.
void execute (u8 opcode)
Executes a single opcode.
template<typename T , T_ITERATOR_SFINAE >
void load (T begin, T end, usize offset=0, bool auto_reset_vector=false)
Loads data into cardbus.
void load_state (const cpu_state &new_state)
Load CPU state.
cpu_state save_state () const
Save CPU state.
bool is_halted () const
Check if the CPU is halted.
void clear ()
Reset the CPU.
Test related methods.
void do_pseudo_bdos (bool should)
Set the CPU to resolve calls to BDOS internally.
void set_pseudo_bdos_redirect (const char *filename)
Redirect pseudo BDOS print routines to a file.
void reset_pseudo_bdos_redirect ()
Redirect pseudo BDOS print routines back to stdout.
Interrupt related methods.
void interrupt (std::array< u8, 3 > inst)
Call an interrupt and push PC, then disable interrupts.
Detailed Description
template<class bus_iface = bus&>
class cpu< bus_iface >
Represents the CPU of the emulator.
This is the 8080 CPU emulator and interpreter. It abstracts the CPU functionality into straightforward methods and presents a way to step and interact with state. Being an interpreter, each opcode starting from the program counter address in cardbus is fetched and executed according to what it represents and including further fetches to opcode operands. The API also provides public access to execute(), should the user want to manually ask for instructions.
Note
The class is completely defined in this header to allow templating the class to determine what bus interface bus_iface to use. For example, you can:
cpu<bus&> cpu(cardbus); or cpu<> cpu(cardbus); to create a standard CPU that interacts with a bus, or
cpu<std::array<u8, 65536>> cpu; to instead have an empty array as a bus, for max performance!
Member Function Documentation
do_pseudo_bdos()
template<class bus_iface = bus&> void cpu< bus_iface >::do_pseudo_bdos (bool should) inline
Set the CPU to resolve calls to BDOS internally.
Parameters
should Whether the CPU should handle BDOS calls.
This method enables pseudo BDOS functionality by the CPU itself. This can be essential for testing the CPU, as most diagnostic programs expect the system to be able to print messages.
execute() [1/2]
template<class bus_iface = bus&> void cpu< bus_iface >::execute (u8 opcode) inline
Executes a single opcode.
Parameters
opcode The opcode to execute.
This method is a comprehensive jump table for all the opcodes the 8080 CPU can execute. It effectively groups the decode and execute phases of the CPU into a single method, and is used by the step method to execute instructions.
Note
To allow multiple operand instructions, there is an overload of this method that takes one or two extra argument bytes and temporarily redirects fetch() and fetch2() to them during the instruction cycle!
execute() [2/2]
template<class bus_iface = bus&> void cpu< bus_iface >::execute (u8 opcode, u8 operand1, u8 operand2 = 0) inline
Executes a single opcode with one or two operands.
Parameters
opcode The opcode to execute.
operand1 The first operand to the opcode.
operand2 The second operand to the opcode.
This is an overload that manipulates the way the fetch cycles interact in the CPU logic: it will use the operands retrieved by this method (usually to be placed by a device on the bus that called an IRQ) instead of fetching them from the bus cards. In fact, this is used by the interrupt method as well.
Referenced by cpu< bus_iface >::interrupt(), and cpu< bus_iface >::step().
interrupt()
template<class bus_iface = bus&> void cpu< bus_iface >::interrupt (std::array< u8, 3 > inst) inline
Call an interrupt and push PC, then disable interrupts.
Parameters
inst The interrupt instruction (with optional operands) to execute out of place.
Todo:
This allows any instruction and any retrieval of arguments, but I'm not sure if that happens other than on CALL.
References cpu< bus_iface >::execute().
is_halted()
template<class bus_iface = bus&> bool cpu< bus_iface >::is_halted () const inline
Check if the CPU is halted.
Returns
True if the CPU is halted, false otherwise.
load()
template<class bus_iface = bus&> template<typename T , T_ITERATOR_SFINAE > void cpu< bus_iface >::load (T begin, T end, usize offset = 0, bool auto_reset_vector = false) inline
Loads data into cardbus.
Parameters
begin Iterator to the beginning of data.
end Iterator to the end of data.
offset Offset to try to start loading at.
auto_reset_vector Whether the zero page should point to the start of loaded data automatically.
Exceptions
<tt>std::out_of_range</tt> if data won't fit in cardbus.
<tt>std::out_of_range</tt> if enabled auto reset vector will overwrite the first few bytes loaded.
This method can be useful to load programs, libraries, or data into the emulator's cardbus. It will copy the data at the specified offset, check if it will fit, and if auto_reset_vector is true, it will set the zero page (the first 3 bytes of cardbus, specifically a jump instruction and a 2 byte argument) to point to the start of the loaded data.
Note
This method calls write_force() on the cards when using a bus, so it can also write to locked ROM to setup the system roms.
load_state()
template<class bus_iface = bus&> void cpu< bus_iface >::load_state (const cpu_state & new_state) inline
Load CPU state.
Parameters
new_state The state to load.
This method can set a new state to the CPU, including all registers and flags of it.
save_state()
template<class bus_iface = bus&> cpu_state cpu< bus_iface >::save_state () const inline
Save CPU state.
Returns
The current state of the CPU.
This method will return the current state of the CPU, including all registers and flags of it.
set_pseudo_bdos_redirect()
template<class bus_iface = bus&> void cpu< bus_iface >::set_pseudo_bdos_redirect (const char * filename) inline
Redirect pseudo BDOS print routines to a file.
Parameters
filename The name of the file to print to.
References util::print_helper::set().
step()
template<class bus_iface = bus&> void cpu< bus_iface >::step (usize steps = 1) inline
Steps the CPU by one instruction (and its operands).
Parameters
steps The number of steps to forward the CPU by.
Calling the step method will fetch the next instruction opcode from cardbus and execute it. Internally, on every fetch the PC is incremented, and each instruction is also responsible for fetching its operands, so a step is effectively a full instruction step.
If the CPU is set to handle BDOS calls, it will provide some pseudo BDOS functionality, currently only for printing characters and strings to wherever the printer is set to, stdout by default.
Note
If the CPU is halted, this method will return immediately.
Note
Internally, this method is calling execute(fetch()).
References cpu< bus_iface >::execute().
The documentation for this class was generated from the following file:
src/core/cpu/cpu.hpp