buddy8800: bus Class Reference
bus Class Reference
Represents the S-100 bus of the emulator.
#include <bus.hpp>
Public Member Functions
void insert (card *card, usize slot, bool allow_conflict=false)
Inserts a card into a slot on the bus.
void remove (usize slot)
Removes a card from a slot on the bus.
constexpr usize size () const
Returns the maximum number of addressable locations on the bus.
u8 read (u16 adr, bool ior=false) const
Reads a byte from the bus.
void write (u16 adr, u8 byte, bool iow=false)
Writes a byte to the bus.
void write_force (u16 adr, u8 byte, bool iow=false)
Writes a byte to the bus, without considering write lock.
bus_index_iface operator[] (u16 adr)
Indexes the bus.
u8 operator[] (u16 adr) const
A shortcut to read the bus using an index directly without a proxy object.
void refresh ()
Refreshes all cards on the bus.
bool is_irq () const
Checks if an IRQ is raised.
std::array< u8, 3 > get_irq ()
Gets the IRQ instruction (and possible operands).
std::string bus_map_s () const
Returns a detailed map of the bus.
u8 get_slot_by_adr (u16 adr) const
Get in which slot a card is according to an address.
void clear ()
Clears all cards on the bus.
Detailed Description
Represents the S-100 bus of the emulator.
This class holds the necessary structures and methods to handle inter-operation of the Intel 8080 CPU with any assortment of cards interacting through a data, address, and control bus according to the S-100 specs, including interrupt vectors.
A design choice was made to try to stay as close as possible as an indexable array of memory with the bus, so that it can be easily replaced by a simple std::array<u8, 65536>. This is why the read() and write() methods are called by an additional middle class, bus_index_iface, which acts as a proxy to address locations and call reads and writes by the cast and assignment operators.
Note
Conflicting address ranges are allowed but must be explicitly toggled by an insert(). Make sure you actually want a conflict, since cards have an IOR/IOW signal that can be used to determine if the cards belong to memory or I/O addressable ranges, which can overlap but be separated by the IOR/IOW signal being set or not.
Note
The CPU, while in reality is placed on a card, it's not here. The bus acts as glue between the plentitude of cards and the CPU itself.
Warning
This class does not own the cards, and it's up to other parts of the emulator to manage the card memory, such as system_config.
Warning
The size() method returns the maximum number of addressable locations on the bus (65536), not the number of cards. While this might look misleading, it's actually an attempt at keeping the same interface as there would be if the instanced bus were to be replaced by a normal std::array<u8, 65536>.
Todo:
The design iterating over all of the cards array and calling methods and dereferencing pointers is inefficient, instead it could be faster to hold vectors to different types of cards and iterate over them separately only on the related bus methods. For example, data cards don't need to be refreshed. Or consider a faster way to implement the refresh method, since right now it is called at every CPU step...
Member Function Documentation
bus_map_s()
std::string bus::bus_map_s () const inline
Returns a detailed map of the bus.
Returns
A std::string with details about the bus devices.
This method will return a very long std::string containing the address map of the bus, showing the start and end addresses of each card, along with the card's type (name) and additional details.
Note
The output for each device is formatted as follows:
slot: [is-i/o] start-address-hex/address-range: card-type, card-details
References util::to_hex_s().
clear()
void bus::clear () inline
Clears all cards on the bus.
This method will call each card's possibly distinct way to clear, which will depend on the type of card, some will clear data, others might reset configuration settings.
References card::clear().
get_irq()
std::array<u8, 3> bus::get_irq () inline
Gets the IRQ instruction (and possible operands).
Returns
An instruction according to the type of interrupt the device uses to send.
Exceptions
std::runtime_error if no IRQ is raised.
When the 8080 accepts an interrupt request, it will look for an instruction on the data bus to run. Most commonly this is either a RST or a CALL instruction. While RST has a bunch of fixed offsets, CALL instead makes the 8080 run an extra two fetches for a 16-bit address to jump to. Because of this, an array of 3 bytes has to be returned in case of the latter, otherwise they would be just 0x00.
Note
This method should be called after is_irq() returns true.
Note
The order of returned interrupts is preferential to the order of cards on the bus. This is because many S-100 systems used simple daisy-chaining for IRQs, and the closest slot to raise an IRQ concurrent to another would be the first to be serviced.
Todo:
Verify this last claim (we may need an 8259 PIC instead...).
References card::get_irq(), and card::is_irq().
get_slot_by_adr()
u8 bus::get_slot_by_adr (u16 adr) const inline
Get in which slot a card is according to an address.
Returns
The slot closest that accepts the address in its range, 255 if none.
insert()
void bus::insert (card * card, usize slot, bool allow_conflict = false) inline
Inserts a card into a slot on the bus.
Parameters
card A pointer to the card to insert.
slot The slot number to insert the card into, counting from 0 to MAX_BUS_CARDS - 1.
allow_conflict Whether to allow bus conflicts (run a conflict check) or not.
Exceptions
std::invalid_argument if the card is nullptr.
std::out_of_range if the slot is out of range.
std::invalid_argument if the slot is already occupied.
std::invalid_argument if a bus conflict is detected and allow_conflict is false.
Warning
This method allows a bus conflict, but in such event, only the earlier slot card will be able to be read from!
is_irq()
bool bus::is_irq () const inline
Checks if an IRQ is raised.
Returns
True if an IRQ is raised, false otherwise.
Note
This method should be a condition for a loop at the end of an emulation cycle, so that all IRQs can be handled if occasionally concurrent.
References card::is_irq().
operator[]() [1/2]
bus_index_iface bus::operator[] (u16 adr) inline
Indexes the bus.
Parameters
adr The address to index.
Returns
A proxy object to index the bus.
operator[]() [2/2]
u8 bus::operator[] (u16 adr) const inline
A shortcut to read the bus using an index directly without a proxy object.
Parameters
adr The address to index.
Returns
The byte read from the bus.
References read().
read()
u8 bus::read (u16 adr, bool ior = false) const inline
Reads a byte from the bus.
Parameters
adr The address to read from.
ior Whether the IOR signal is set or not.
Returns
The byte read from the first valid card on the bus.
Warning
This method will return only the first valid card slot that is in range of the address. Be mindful of allowed collision ranges.
References card::in_range(), card::is_io(), and card::read().
Referenced by operator[]().
refresh()
void bus::refresh () inline
Refreshes all cards on the bus.
This method will call each card's possibly distinct way to refresh, which is important for example to let a serial card be able to poll or send new data.
Note
It is very important that cards implement ways to not make this method slow down the emulation, since it's highly likely that many devices would operate at rates much slower than the CPU clock step, thus it's beneficial to add a cycle counter to the method implementation on the card.
References card::refresh().
remove()
void bus::remove (usize slot) inline
Removes a card from a slot on the bus.
Parameters
slot The slot number to remove the card from.
Exceptions
std::out_of_range if the slot is out of range.
size()
constexpr usize bus::size () const inline constexpr
Returns the maximum number of addressable locations on the bus.
Returns
The maximum number of addressable locations on the bus.
Warning
This method returns a fixed value of max addressable locations on the bus (65536), not the number of cards!
write()
void bus::write (u16 adr, u8 byte, bool iow = false) inline
Writes a byte to the bus.
Parameters
adr The address to write to.
byte The byte to write.
iow Whether the IOW signal is set or not.
Note
This method will write to all cards in range of the address. Be mindful of allowed collision ranges.
References card::in_range(), card::is_io(), and card::write().
write_force()
void bus::write_force (u16 adr, u8 byte, bool iow = false) inline
Writes a byte to the bus, without considering write lock.
Parameters
adr The address to write to.
byte The byte to write.
iow Whether the IOW signal is set or not.
Note
This method will write to all cards in range of the address.
References card::in_range(), card::is_io(), and card::write_force().
The documentation for this class was generated from the following file:
src/core/bus/bus.hpp