buddy8800: pty Class Reference
pty Class Reference
Represents a pseudo-terminal interface.
#include <unix_pty.hpp>
Public Member Functions
void open ()
Open the PTY interface.
const char * name () const
Retrieve the name of the slave device.
void send (const char *data) const
Send data to the PTY interface master side.
void send (const char *data, usize size) const
Send data to the PTY interface master side.
void send_break () const
Send a break signal to the PTY interface master side.
char getch () const
Get a single byte from the PTY interface master side.
void putch (char c) const
Send a single byte to the PTY interface master side.
bool poll () const
Check if there is data available to be read from the PTY interface master side.
void recv (char *data, usize max, char terminator='\r') const
Receive data from the PTY interface master side.
void setup (u32 data_bits, pty_parity parity, u32 stop_bits)
Setup the PTY interface with custom configuration.
void set_baud_rate (u32 baud_rate)
Set the baud rate of the PTY interface.
void set_echo_received_back (bool should)
Set whether received data should be printed back to the PTY slave side.
void close ()
Close the PTY interface and free the PTY master file descriptor.
Detailed Description
Represents a pseudo-terminal interface.
This class handles a PTY interface and provides some convenience when interacting with it. After construction and by calling open(), the PTY interface is opened and public methods from this class can be used to handle the master file descriptor side of the PTY. The slave side is supposed to be provided to the user or a process to interact with, thus the name() method is available to retrieve the slave device name, but no further handling is done by this class.
Todo:
On breaking the application while running, if anything is connected to the slave fd, the PTY is never closed.
Member Function Documentation
getch()
char pty::getch () const
Get a single byte from the PTY interface master side.
Returns
The byte read from the PTY interface.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
This method reads a single byte/char from the PTY interface master side. It uses the read() system call to read the byte from the master file descriptor, sent by the slave side.
Warning
This method will block until a byte is read.
References putch().
Referenced by recv(), and serial_card::refresh().
name()
const char * pty::name () const
Retrieve the name of the slave device.
Returns
A C-like string containing the name of the slave device.
This method returns the name of the slave device, such as /dev/pts/3. This name identifies the slave side PTY interface, to which a user or process can interface with. For example, you could run screen /dev/pts/3 on your terminal to connect to the PTY slave side.
Referenced by serial_card::identify().
open()
void pty::open ()
Open the PTY interface.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface could not be opened.
Use this method when first starting the PTY interface. It will open the master file descriptor and setup various configuration flags for a bit more realism in emulating an Altair 8800 serial interface.
Note
The default setup configuration is 300 baud, 8 data bits, no parity and 1 stop bit. B300-8N1
References set_baud_rate(), and setup().
poll()
bool pty::poll () const
Check if there is data available to be read from the PTY interface master side.
Returns
Whether there is data available to be read.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
This method polls the PTY interface master side to check if there is data available to be read. It's handling the master PTY fd internally using epoll.
Referenced by serial_card::refresh().
putch()
void pty::putch (char c) const
Send a single byte to the PTY interface master side.
Parameters
c The byte to be sent.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
This method sends a single byte/char to the PTY interface master side. It uses the write() system call.
Warning
This method will block until the byte is sent.
Referenced by getch(), and serial_card::refresh().
recv()
void pty::recv (char * data, usize max, char terminator = '\r') const
Receive data from the PTY interface master side.
Parameters
data A pointer to the buffer where the data will be stored.
max The amount of bytes to be read, usually the size of the buffer.
terminator The character that will stop the reading.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
<tt>std::invalid_argument</tt> if max is 0.
This method reads data from the PTY interface master side. It will read up to max - 1 bytes, until the terminator character is found. The received data is always null-terminated by this method, thus max is actually considered as max - 1 for the amount of bytes to be read, with the last byte being reserved for the null-terminator, should data fit the entire buffer.
Note
If max is 1, the method is a wrapper to getch() and will not null-terminate the buffer.
Warning
This method will block until max - 1 bytes are read or the terminator character is found.
References getch(), and send().
send() [1/2]
void pty::send (const char * data) const
Send data to the PTY interface master side.
Parameters
data A pointer to the data to be sent.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
This method is a wrapper around the send(const char* data, usize size) method, where size simply is provided by the length of the passed string using std::strlen().
Warning
This method will block until all bytes of data are sent.
Referenced by recv().
send() [2/2]
void pty::send (const char * data, usize size) const
Send data to the PTY interface master side.
Parameters
data A pointer to the data to be sent.
size The amount of bytes to be sent starting from data.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
This method sends data to the PTY interface master side. The slave side will be able to receive this data in order. It uses the write() system call to send the data to the master file descriptor.
Warning
This method will block until size bytes are sent.
send_break()
void pty::send_break () const
Send a break signal to the PTY interface master side.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface had an error.
This method sends a break signal to the PTY interface master side. It uses the tcsendbreak() system call to make the pseudo-terminal interface run a break signal.
Sending a break signal effectively holds the transmission line low for a considerable amount of time, with no concern for framing or data bits, which is a step further than simply sending 0x00 over and over.
set_baud_rate()
void pty::set_baud_rate (u32 baud_rate)
Set the baud rate of the PTY interface.
Parameters
baud_rate The baud rate to be set.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface could not be configured.
This method sets the baud rate of the PTY interface. It uses the cfsetospeed() and cfsetispeed() functions from termios.h to set the baud rate of the PTY interface.
Referenced by open(), and serial_card::write().
set_echo_received_back()
void pty::set_echo_received_back (bool should)
Set whether received data should be printed back to the PTY slave side.
Parameters
should Whether received data should be echoed.
setup()
void pty::setup (u32 data_bits, pty_parity parity, u32 stop_bits)
Setup the PTY interface with custom configuration.
Parameters
data_bits The amount of data bits to be used.
parity The parity mode to be used.
stop_bits The amount of stop bits to be used.
Exceptions
<tt>std::runtime_error</tt> if the PTY interface could not be configured.
<tt>std::invalid_argument</tt> if an invalid setup was being configured.
This method sets up the PTY interface with custom configuration. Internally, this makes extensive use of termios.h functionality and its functions to configure the PTY interface.
Referenced by open(), and serial_card::write().
The documentation for this class was generated from the following files:
src/core/iface/unix_pty.hpp
src/core/iface/unix_pty.cpp