[emulator]
pseudo_bdos_enabled = false
start_with_pc_at    = 0xf800

[[card]] # Load 8K BASIC in RAM (0x0000-0x1fff)
slot        = 0
type        = "ram"
at          = 0x0000
load        = "8kbas.bin"

[[card]] # Add 16K empty RAM (0x8000-0xbfff)
slot        = 1
type        = "ram"
at          = 0x8000
range       = 16384

[[card]] # Put Altair Monitor in ROM (0xf800-0xfc00)
slot        = 2
type        = "rom"
at          = 0xf800
load        = "altmon.bin"

[[card]] # 88-2SIO serial interface
slot        = 3
type        = "serial"
at          = 0x10
